# Generated by Django 5.1 on 2024-10-16 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_rename_image_project_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_contact', models.CharField(max_length=255)),
                ('organisation_phone_number', models.CharField(max_length=15)),
                ('organisation_email', models.EmailField(max_length=254, unique=True)),
                ('organisation_image_url', models.URLField(blank=True, null=True)),
                ('organisation_ABN', models.CharField(max_length=11, unique=True)),
                ('is_charity', models.BooleanField()),
                ('owners', models.ManyToManyField(related_name='owned_organisations', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_projects', to='projects.project')),
                ('staff', models.ManyToManyField(related_name='staff_organisations', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
