# Generated by Django 5.1 on 2024-10-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_contact', models.CharField(max_length=255)),
                ('organisation_phone_number', models.CharField(max_length=15)),
                ('organisation_email', models.EmailField(max_length=254, unique=True)),
                ('organisation_image_url', models.URLField(blank=True, null=True)),
                ('organisation_ABN', models.CharField(max_length=11, unique=True)),
                ('is_charity', models.BooleanField(default=False)),
            ],
        ),
    ]
