# Generated by Django 5.1 on 2024-10-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationprofile',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='is_charity',
            field=models.BooleanField(default=False),
        ),
    ]
