# Generated by Django 5.1 on 2024-10-20 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationprofile',
            name='owners',
            field=models.ManyToManyField(related_name='owned_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='staff',
            field=models.ManyToManyField(related_name='staff_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
