# Generated by Django 5.1 on 2024-11-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationprofile',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='organisationprofile',
            name='staff',
        ),
    ]
