# Generated by Django 5.1 on 2024-11-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_remove_organisationprofile_owners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationprofile',
            name='organisation_email',
        ),
        migrations.RemoveField(
            model_name='organisationprofile',
            name='organisation_image_url',
        ),
    ]
