# Generated by Django 5.1 on 2024-10-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('projects', '0004_rename_image_project_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organisations.organisationprofile'),
        ),
    ]
